# Generated by Django 3.1.7 on 2021-05-17 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildernis', '0003_auto_20210517_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='progress',
            name='image',
            field=models.ImageField(upload_to='wildernis/media/images'),
        ),
    ]
