# Generated by Django 3.1.7 on 2021-05-18 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildernis', '0005_auto_20210518_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='image',
            field=models.ImageField(upload_to='data/plants/images'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='afbeelding',
            field=models.ImageField(upload_to='data/imagse/progress'),
        ),
    ]
