# Generated by Django 3.1.7 on 2021-03-17 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20210317_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('Face masks', 'Face masks'), ('Outdoor & Garden', 'Outdoor & Garden'), ('Wall decor', 'Wall decor'), ('Self Care', 'Self care'), ('Gift Ideas', 'Gift ideas'), ('Other', 'Other')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
