# Generated by Django 3.1.7 on 2021-03-17 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('Face masks', 'Face masks'), ('Outdoor & Garden', 'Outdoor & Garden'), ('Wall decor', 'Wall decor'), ('Self Care', 'Self care'), ('Gift Ideas', 'Gift ideas'), ('Other', 'Other')], max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cats', to='auctions.category'),
        ),
    ]
